# Generated by Django 2.2.7 on 2019-12-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191215_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='abstract',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
