# Generated by Django 2.2.7 on 2019-12-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191216_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'django'), (2, 'djangovue'), (3, 'devops')], default=3),
        ),
    ]
